In [4]:
import pandas as pd
import numpy as np
from scipy import stats


d1 = np.random.choice(range(8,18),(1,2))
d2 = np.random.choice(range(28,41),(1,2))
data = np.concatenate((d1, d2), axis=0)


observations = pd.DataFrame(data,
                            index=['Дождь','Солнце'],
                            columns=['Верные ответы волшебника','Неверные ответы'])




In [5]:
d1

array([[17, 12]])

In [6]:
d2

array([[29, 39]])

In [7]:
data

array([[17, 12],
       [29, 39]])

In [8]:
observations = pd.DataFrame(data,
                            index=['Дождь','Солнце'],
                            columns=['Верные ответы волшебника','Неверные ответы'])

In [9]:
observations

Верные ответы волшебника  Неверные ответы
Дождь                         17               12
Солнце                        29               39

In [ ]:
# H0 - выборки не зависимы
# H1 - выборки зависимы


stat, p = stats.ttest_ind(data, observations)
if p < 0.05:
    print('Отклоняем нулевую гипотезу. Есть некоторая зависимость')
else:
    print('Не отклоняем нулевую гипотезу. Выборки, вероятно, независимы')