# Домашнее задание «Библиотека numpy. Вычислительные задачи»

In [1]:
import numpy as np

## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
N = 10

a = np.arange(N - 1, -1, -1)

In [4]:
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [5]:
type(a)

numpy.ndarray

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [11]:
N = 10

m = np.diag(np.arange(N - 1, -1, -1), k=0)
m

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
# выводим элементы главной диагонали в виде вектора
np.diagonal(m)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
# сумма значений элементов главной диагонали
np.trace(m)

45

## Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3 

In [14]:
# вводим коэффициенты левой части

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [15]:
# вводим коэффициенты правой части

b = np.array( [4, 12, -3] )

In [16]:
from numpy import linalg

In [17]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

## Задание 4
В материалах занятия раздел “Задача 4 домашнего задания” 

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [20]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

users_stats

array([[2, 1, 0, 0, 0, 0],
       [1, 1, 2, 1, 0, 0],
       [2, 0, 1, 0, 0, 0],
       [1, 1, 2, 1, 0, 1],
       [0, 0, 1, 2, 0, 0],
       [0, 0, 0, 0, 0, 5],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 3],
       [1, 0, 0, 2, 1, 4]])

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [21]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [24]:
num_user = 0 # номер самого похожего пользователя
max_ = 0 # максимальный cos

In [30]:
next_user_length = np.linalg.norm(next_user_stats)

In [34]:
for i, user in enumerate(users_stats):
    user_lenght = np.linalg.norm(user)
    cos_ = np.dot(next_user_stats, user) / (next_user_length * user_lenght)
    if max_ < cos_:
        num_user = i + 1
        max_ = cos_    

In [35]:
num_user

8